# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Gigel3d
subtitle: "Tech Art Learning Materials"
name: "Paweł Stachowicz"
email: gigel3d@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Tech Art learning materials for Houdini, Unreal, Blender and Substance. 
twitter_username: username
github_username: username
minimal_mistakes_skin: dark
search: true

# Build settings
markdown: kramdown
remote_theme: mmistakes/minimal-mistakes
# Outputting
permalink: /:categories/:title/
paginate: 5 # amount of posts to show
paginate_path: /page:num/
timezone: # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones

include:
  - _pages

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

author:
  name   : "Paweł Stachowicz"
  avatar : "/assets/images/author.png"
  bio    : "Technical Artist"
  links:
    - label: "Artstation"
      icon: "fa-brands fa-artstation"
      url: "https://www.artstation.com/gigel"
    - label: "X"
      icon: "fa-brands fa-x-twitter"
      url: "https://x.com/Gigel3d"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/gigel3d"
    - label: "YouTube"
      icon: "fa-brands fa-youtube"
      url: "https://www.youtube.com/channel/UCv25KtK5ViaY0wwmiuHbIjw"

footer:
  links:
    - label: "Artstation"
      icon: "fa-brands fa-artstation"
      url: "https://www.artstation.com/gigel"
    - label: "X"
      icon: "fa-brands fa-x-twitter"
      url: "https://x.com/Gigel3d"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/gigel3d"
    - label: "YouTube"
      icon: "fa-brands fa-youtube"
      url: "https://www.youtube.com/channel/UCv25KtK5ViaY0wwmiuHbIjw"

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      show_date: true
      layout: single
      author_profile: false
      read_time: true
      words_per_minute: 250
      comments: true
      share: true
      related: true
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true
  # _portfolio
  - scope:
      path: "_portfolio"
      type: portfolio
    values:
      layout: single
      author_profile: false
      share: true
  # _photography
  - scope:
      path: ""
      type: photography
    values:
      layout: single
      author_profile: false
      share: true
      
category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/

teaser: "/assets/images/500x300.png"
logo: "/assets/images/88x88.png"
# masthead_title: "Tech Art Learning Materials"
enable_copy_code_button: true
atom_feed:
  hide: true
timezone: Poland

# socials
twitter:
  username: "Gigel3d"
social:
  type:  Person # Person or Organization (defaults to Person)
  name:  Gigel3d # If the user or organization name differs from the site's name
  links:
    - "https://x.com/Gigel3d"

# collections
collections:
portfolio:
  output: true
  permalink: /:collection/:path/

# Collections
collections:
  photography:
    output: true
    permalink: /:collection/:path/
